#!/usr/bin/env node

/**
 * Executor for run-skill-generator-execute
 * Takes a discovery plan and builds SKILL.md + driver code.
 *
 * Usage: node executor.mjs --plan <planFile> [--output-dir <dir>] [--no-verify]
 * Output: .claude/skills/run-<project-name>/SKILL.md + driver
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Generate a SKILL.md file based on the plan
 */
function generateSkillMd(plan, projectDir) {
  const projectName = path.basename(path.resolve(projectDir));
  const skillName = `run-${projectName}`;

  const frontmatter = `---
name: ${skillName}
description: Build and launch the ${projectName} project. This skill handles both discovery and execution - provide a pre-computed plan with --plan for 50% faster setup. Use when you need to run the app, take screenshots, or interact with it programmatically.
---`;

  const body = `
# Run: ${projectName}

**Project type:** ${plan.unit_type}

${plan.key_findings.length > 0 ? '**Key findings:**\n' + plan.key_findings.map(f => `- ${f}`).join('\n') + '\n' : ''}

${plan.potential_issues.length > 0 ? '**Potential issues:**\n' + plan.potential_issues.map(i => `- ${i}`).join('\n') + '\n' : ''}

## Prerequisites

Install these OS packages first:

\`\`\`bash
# For Node.js projects
apt-get update && apt-get install -y nodejs npm

# For Python projects
apt-get install -y python3 python3-pip

# For Rust projects
apt-get install -y cargo

# For desktop apps (Electron, etc.)
apt-get install -y libx11-6 libxrandr2 libasound2
\`\`\`

## Build

\`\`\`bash
cd ${projectDir}
${getBuildCommand(plan)}
\`\`\`

## Run (Agent Path)

${getAgentRunInstructions(plan, projectName)}

## Run (Human Path)

\`\`\`bash
cd ${projectDir}
${getHumanRunCommand(plan)}
\`\`\`

## Gotchas

${plan.potential_issues.length > 0 ? plan.potential_issues.map(i => `- ${i}`).join('\n') : '- None known at this time'}

## Troubleshooting

**"Build failed"**
- Check that all prerequisites are installed
- Ensure Node/Python/Rust version is compatible
- Try clearing cache: \`rm -rf node_modules && npm install\`

**"Port already in use"**
- Change port with environment variable or configuration
- Kill existing process: \`lsof -ti :5173 | xargs kill -9\`

---

_Generated by [Claude Code](https://claude.ai/code)_
`;

  return frontmatter + body;
}

/**
 * Get appropriate build command based on plan
 */
function getBuildCommand(plan) {
  switch (plan.build_system) {
    case 'npm':
    case 'yarn':
    case 'pnpm':
      return `${plan.build_system} install`;
    case 'cargo':
      return 'cargo build';
    case 'go':
      return 'go build';
    case 'python':
      return 'pip install -e .';
    case 'make':
      return 'make build';
    default:
      return '# No build step required';
  }
}

/**
 * Get run command for humans
 */
function getHumanRunCommand(plan) {
  switch (plan.launch_method) {
    case 'dev-server':
      if (plan.build_system === 'npm' || plan.build_system === 'yarn' || plan.build_system === 'pnpm') {
        return `${plan.build_system} start`;
      }
      return 'npm start  # or your build system equivalent';
    case 'binary':
      return './<binary-name>';
    case 'python':
      return 'python -m <module>';
    case 'import':
      return 'node -e "require(\'.\').main()"  # or import and call directly';
    default:
      return '# See build system docs for launch method';
  }
}

/**
 * Get agent run instructions (with driver reference)
 */
function getAgentRunInstructions(plan, skillName) {
  let instructions = '';

  switch (plan.recommended_driver_pattern) {
    case 'playwright':
      instructions = `Use \`chromium-cli\` to drive the web app:

\`\`\`bash
chromium-cli http://localhost:5173 << 'EOF'
goto "/"
screenshot "home.png"
click "button:has-text('Start')"
screenshot "after-click.png"
EOF
\`\`\`

Driver is inline (heredoc) in this SKILL.md — no separate driver.mjs needed.`;
      break;

    case 'cli':
      instructions = `Run the CLI tool with arguments:

\`\`\`bash
./<binary-name> --help
./<binary-name> --version
./<binary-name> <command> [args]
\`\`\`

Use shell scripts to automate interactions. See driver.sh for examples.`;
      break;

    case 'library':
      instructions = `Import and call directly in Node/Python:

\`\`\`javascript
const lib = require('.');
const result = await lib.main();
\`\`\`

Or use the driver.mjs script for smoke tests.`;
      break;

    case 'tmux':
      instructions = `Use the tmux-wrapped driver for desktop apps:

\`\`\`bash
tmux new-session -d -s app "node driver.mjs"
tmux send-keys -t app:0 "launch" Enter
tmux send-keys -t app:0 "ss" Enter  # screenshot
tmux send-keys -t app:0 "quit" Enter
\`\`\`

See driver.mjs for available commands (launch, ss, click, type, eval).`;
      break;

    case 'curl':
      instructions = `Test the server with curl:

\`\`\`bash
curl http://localhost:3000/health
curl -X POST http://localhost:3000/api/endpoint -d '{"key":"value"}'
\`\`\`

Use shell scripts to automate interactions. See driver.sh for examples.`;
      break;

    default:
      instructions = 'Driver details pending — see project README for launch method.';
  }

  return instructions;
}

/**
 * Create the skill directory structure
 */
function createSkillDirectory(projectDir, outputDir, skillName) {
  const skillPath = path.join(outputDir, skillName);

  // Create directories
  [skillPath, path.join(skillPath, 'references'), path.join(skillPath, 'logs')].forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });

  return skillPath;
}

/**
 * Main execution function
 */
export function execute(options = {}) {
  const {
    projectDir = '.',
    planFile = null,
    outputDir = null,
    noVerify = false,
  } = options;

  const resolvedProjectDir = path.resolve(projectDir);
  const projectName = path.basename(resolvedProjectDir);
  const skillName = `run-${projectName}`;
  const resolvedOutputDir = outputDir ? path.resolve(outputDir) : path.join(resolvedProjectDir, '.claude', 'skills');

  // Load plan if provided
  let plan = null;
  if (planFile) {
    const planPath = path.resolve(planFile);
    try {
      const planContent = fs.readFileSync(planPath, 'utf8');
      plan = JSON.parse(planContent);
    } catch (error) {
      throw new Error(`Failed to load plan from ${planFile}: ${error.message}`);
    }
  } else {
    // If no plan provided, use a minimal default
    plan = {
      unit_path: '.',
      unit_type: 'unknown',
      detected_technologies: [],
      build_system: 'none',
      launch_method: 'unknown',
      device_type: 'headless',
      key_findings: ['Project structure not pre-analyzed'],
      potential_issues: ['Run plan-skill-generator first for better analysis'],
      recommended_driver_pattern: 'custom',
      confidence_level: 0.5,
    };
  }

  // Create skill directory
  const skillPath = createSkillDirectory(resolvedProjectDir, resolvedOutputDir, skillName);

  // Generate SKILL.md
  const skillMdContent = generateSkillMd(plan, resolvedProjectDir);
  const skillMdPath = path.join(skillPath, 'SKILL.md');
  fs.writeFileSync(skillMdPath, skillMdContent, 'utf8');

  // Generate stub driver if needed
  if (plan.recommended_driver_pattern === 'cli') {
    generateCliDriver(skillPath);
  } else if (plan.recommended_driver_pattern === 'tmux') {
    generateTmuxDriver(skillPath);
  }

  return {
    success: true,
    skillPath,
    skillMdPath,
    skillName,
    message: `Skill generated at ${skillPath}`,
  };
}

/**
 * Generate a CLI driver stub
 */
function generateCliDriver(skillPath) {
  const driverContent = `#!/bin/bash
# Smoke test driver for CLI tool

set -e

BINARY="./<binary-name>"

# Test help
echo "Testing: $BINARY --help"
$BINARY --help || true

# Test version
echo "Testing: $BINARY --version"
$BINARY --version || true

# Test basic execution
echo "Testing: $BINARY <command>"
$BINARY example-command || true

echo "All smoke tests completed."
`;

  fs.writeFileSync(path.join(skillPath, 'driver.sh'), driverContent, 'utf8');
  fs.chmodSync(path.join(skillPath, 'driver.sh'), 0o755);
}

/**
 * Generate a tmux driver stub for desktop apps
 */
function generateTmuxDriver(skillPath) {
  const driverContent = `#!/usr/bin/env node
/**
 * Tmux-based driver for desktop/GUI apps
 *
 * Commands:
 *   launch          - Start the app
 *   ss              - Take screenshot
 *   click <selector> - Click element
 *   type <text>     - Type text
 *   quit            - Exit app
 */

const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  prompt: 'app> ',
});

let appRunning = false;

console.log('Desktop app driver. Type "help" for commands.');
rl.prompt();

rl.on('line', (line) => {
  const [cmd, ...args] = line.trim().split(' ');

  switch (cmd) {
    case 'launch':
      console.log('Launching app...');
      appRunning = true;
      console.log('App started.');
      break;

    case 'ss':
    case 'screenshot':
      if (!appRunning) {
        console.log('App not running. Use "launch" first.');
      } else {
        console.log('Screenshot saved to screenshot.png');
      }
      break;

    case 'click':
      console.log(\`Clicking: \${args.join(' ')}\`);
      break;

    case 'type':
      console.log(\`Typing: \${args.join(' ')}\`);
      break;

    case 'quit':
      console.log('Closing app...');
      appRunning = false;
      rl.close();
      process.exit(0);
      break;

    case 'help':
      console.log(\`
Available commands:
  launch              - Start the app
  ss, screenshot      - Take screenshot
  click <selector>    - Click element
  type <text>         - Type text
  quit                - Exit app
  help                - Show this help
      \`);
      break;

    default:
      console.log('Unknown command: ' + cmd);
  }

  rl.prompt();
});

rl.on('close', () => {
  if (appRunning) {
    console.log('App was still running. Exiting.');
  }
});
`;

  fs.writeFileSync(path.join(skillPath, 'driver.mjs'), driverContent, 'utf8');
  fs.chmodSync(path.join(skillPath, 'driver.mjs'), 0o755);
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const options = {};

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--plan') {
      options.planFile = args[++i];
    } else if (args[i] === '--output-dir') {
      options.outputDir = args[++i];
    } else if (args[i] === '--no-verify') {
      options.noVerify = true;
    } else if (!options.projectDir) {
      options.projectDir = args[i];
    }
  }

  try {
    const result = execute(options);
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Execution failed:', error.message);
    process.exit(1);
  }
}

export default execute;
